### ISSUE TITLE
GrovePi not working 

### ISSUE THREAD

**Issue by pgupta408** [edgexfoundry/device-grove-c#10]
Hi,

I followed EdgeX Tutorial and I have problems in setting LEDs as well as geting events in Node-Red. 

My Docker ps:
CONTAINER ID        IMAGE                                                      COMMAND                  CREATED             STATUS              PORTS                                                                                                            NAMES
5fdfdee8fab0        edgexfoundry/docker-export-distro-go-arm64:0.7.1           "/export-distro --co…"   27 minutes ago      Up 26 minutes       0.0.0.0:5566->5566/tcp, 0.0.0.0:48070->48070/tcp                                                                 edgex-export-distro
8b67dadccdee        edgexfoundry/docker-device-grove-c-arm64:1.0.0             "/device-grove/build…"   27 minutes ago      Up 27 minutes       0.0.0.0:49991->49991/tcp                                                                                         edgex-device-grove
ef627e5aa798        edgexfoundry/docker-export-client-go-arm64:0.7.1           "/export-client --co…"   27 minutes ago      Up 27 minutes       0.0.0.0:48071->48071/tcp                                                                                         edgex-export-client
3fe7bb93a7de        edgexfoundry/docker-core-command-go-arm64:0.7.1            "/core-command --con…"   27 minutes ago      Up 27 minutes       0.0.0.0:48082->48082/tcp                                                                                         edgex-core-command
38e6e632376c        edgexfoundry/docker-core-data-go-arm64:0.7.1               "/core-data --consul…"   27 minutes ago      Up 27 minutes       0.0.0.0:5563->5563/tcp, 0.0.0.0:48080->48080/tcp                                                                 edgex-core-data
31e5dfba6d01        edgexfoundry/docker-core-metadata-go-arm64:0.7.1           "/core-metadata --co…"   27 minutes ago      Up 27 minutes       0.0.0.0:48081->48081/tcp, 48082/tcp                                                                              edgex-core-metadata
3030c31a4966        edgexfoundry/docker-support-notifications-go-arm64:0.7.1   "/support-notificati…"   27 minutes ago      Up 27 minutes       0.0.0.0:48060->48060/tcp                                                                                         edgex-support-notifications
23edeb2848a5        edgexfoundry/docker-support-logging-go-arm64:0.7.1         "/support-logging --…"   28 minutes ago      Up 27 minutes       0.0.0.0:48061->48061/tcp                                                                                         edgex-support-logging
67f2dae2abc4        edgexfoundry/docker-edgex-mongo-arm64:0.8.0                "/bin/sh -c /edgex/m…"   29 minutes ago      Up 28 minutes       0.0.0.0:27017->27017/tcp                                                                                         edgex-mongo
b9314fe424b4        consul:1.4.0                                               "docker-entrypoint.s…"   29 minutes ago      Up 28 minutes       0.0.0.0:8400->8400/tcp, 8301-8302/udp, 0.0.0.0:8500->8500/tcp, 8300-8302/tcp, 8600/udp, 0.0.0.0:8600->8600/tcp   edgex-core-consul
e2958adb4fd1        edgexfoundry/docker-edgex-volume-arm64:0.8.0               "/bin/sh -c '/usr/bi…"   29 minutes ago      Up 29 minutes                                                                                                                        edgex-files
pi@pi-desktop:~/demo-grove-pi$ 

pi@pi-desktop:~/demo-grove-pi$ curl -H "Content-Type: application/json" -v -X PUT -d '{"Blue-LED":"true"}' http://localhost:48082/api/v1/device/5cd097cd9f8fc20001d0c11f/command/5cd097cd9f8fc20001d0c117
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 48082 (#0)
> PUT /api/v1/device/5cd097cd9f8fc20001d0c11f/command/5cd097cd9f8fc20001d0c117 HTTP/1.1
> Host: localhost:48082
> User-Agent: curl/7.61.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 19
> 
* upload completely sent off: 19 out of 19 bytes
< HTTP/1.1 400 Bad Request
< Date: Mon, 06 May 2019 22:52:20 GMT
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact

curl command to set blue LED is coming back to bad-request as response. 

What is the problem? 

My Node-Red dashboard is also not showing any events. 

http://localhost:48080/api/v1/event  is showing only 99 events and then no more events after it.. 

It seems that device Service stops running soon after it starts.  

How to debug this problem?

**Comment by BinduRao2018** [comment]
@pgupta408, could you share the logs when the edgex-device-grove container is running

**Comment by BinduRao2018** [comment]
@pgupta408 , Do you still see the problem? Can i close this ticket?
