### ISSUE TITLE
Avoid VERSION discrepancies

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-grove-c#28]
CMake can process the toplevel VERSION file and generate appropriate -D macros to be used in the code for version specification. Look at, eg: [https://github.com/edgexfoundry/device-sdk-c/blob/0030b25982f17bfbd16dc31b18f1d4055c50f917/src/CMakeLists.txt#L12](url)

**Comment by BinduRao2018** [comment]
PR #35 merged to address VERSION discrepancies
