### ISSUE TITLE
Can I use tinker board to connect Grove pi?

### ISSUE THREAD

**Issue by bighb69738** [edgexfoundry/device-grove-c#72]
I tried to connect Grove Pi with Tinker board, but that can not work .
The Error Message:
![Screenshot from 2021-07-27 05-17-31](https://user-images.githubusercontent.com/38970513/127453383-85b4847f-a9e9-4f6d-8ddb-c688f5f3d1fc.png)

**Comment by BinduRao2018** [comment]
device-grove-c service works only with Grove Pi mounted on Raspberry Pi board.

**Comment by bighb69738** [comment]
Thank you @BinduRao2018
